### ISSUE TITLE
HipChat-integration broken (XMPP removed from HipChat?)

### ISSUE THREAD

**Issue by jage** [twingly/marvin#20]
It's been very quiet today, not announcing Pingdom-issues.

```
2018-05-24T09:39:11.383814+00:00 heroku[web.1]: Restarting
2018-05-24T09:39:11.384432+00:00 heroku[web.1]: State changed from up to starting
2018-05-24T09:39:11.941434+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-05-24T09:39:12.027670+00:00 heroku[web.1]: Process exited with status 0
2018-05-24T09:39:13.838723+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat --name Marvin`
2018-05-24T09:39:20.754644+00:00 app[web.1]: up to date in 4.608s
2018-05-24T09:39:22.277052+00:00 heroku[web.1]: State changed from starting to up
2018-05-24T09:39:22.215307+00:00 app[web.1]: [Thu May 24 2018 09:39:22 GMT+0000 (UTC)] INFO Connecting HipChat adapter...
```

After a minute or two it started looping:

```
2018-05-24T09:41:29.968438+00:00 app[web.1]:   at Connector.disconnect (/app/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
2018-05-24T09:41:29.968439+00:00 app[web.1]:   at Connector.onOffline (/app/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
2018-05-24T09:41:29.968440+00:00 app[web.1]:   at emitNone (events.js:86:13)
2018-05-24T09:41:29.968441+00:00 app[web.1]:   at Client.emit (events.js:185:7)
2018-05-24T09:41:29.968446+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/node-xmpp-client/lib/Client.js:157:12)
2018-05-24T09:41:29.968447+00:00 app[web.1]:   at emitNone (events.js:91:20)
2018-05-24T09:41:29.968448+00:00 app[web.1]:   at Connection.emit (events.js:185:7)
2018-05-24T09:41:29.968449+00:00 app[web.1]:   at emitter.end.emitter.disconnect (/app/node_modules/reconnect-core/index.js:108:15)
2018-05-24T09:41:29.968450+00:00 app[web.1]:   at Connection.end.disconnect (/app/node_modules/node-xmpp-core/lib/Connection.js:124:5)
2018-05-24T09:41:29.968451+00:00 app[web.1]:   at Client.Session.end (/app/node_modules/node-xmpp-client/lib/session.js:202:21)
2018-05-24T09:41:29.968452+00:00 app[web.1]:   at Connector.module.exports.Connector.disconnect (/app/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
2018-05-24T09:41:29.968453+00:00 app[web.1]:   at Connector.disconnect (/app/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
2018-05-24T09:41:29.968454+00:00 app[web.1]:   at Connector.onOffline (/app/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
2018-05-24T09:41:29.968455+00:00 app[web.1]:   at emitNone (events.js:86:13)
2018-05-24T09:41:29.968456+00:00 app[web.1]:   at Client.emit (events.js:185:7)
2018-05-24T09:41:29.968456+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/node-xmpp-client/lib/Client.js:157:12)
2018-05-24T09:41:29.968457+00:00 app[web.1]:   at emitNone (events.js:91:20)
2018-05-24T09:41:29.968458+00:00 app[web.1]:   at Connection.emit (events.js:185:7)
2018-05-24T09:41:29.968459+00:00 app[web.1]:   at emitter.end.emitter.disconnect (/app/node_modules/reconnect-core/index.js:108:15)
2018-05-24T09:41:29.968460+00:00 app[web.1]:   at Connection.end.disconnect (/app/node_modules/node-xmpp-core/lib/Connection.js:124:5)
2018-05-24T09:41:29.968461+00:00 app[web.1]:   at Client.Session.end (/app/node_modules/node-xmpp-client/lib/session.js:202:21)
2018-05-24T09:41:29.968462+00:00 app[web.1]:   at Connector.module.exports.Connector.disconnect (/app/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
```

**Comment by jage** [comment]
It looks like HipChat has dropped the XMPP support that we're using under the hoods in Marvin, haven't found anything about the "cloud version" but it seems to have been announced for the on premise hosted version https://confluence.atlassian.com/hipchatkb/hubot-stopped-working-on-hipchat-server-v2-0-7-and-later-867181545.html

**Comment by jage** [comment]
Without having looked into this too much, we might want to consider moving from HipChat instead of trying to fix the HipChat-support (Slack or Stride).

**Comment by walro** [comment]
Yeah, HipChat's days are even more so doomed now...

Just dropping this here: https://slack.com/apps/A0F814AV7-pingdom

With Stride I think we'd need to use https://github.com/atlassian/hubot-stride and do similar stuff to what we do here.

**Comment by walro** [comment]
```
Marvin Pingdom notification·May-23 2:40 AM

Pingdom: News B Search API is up
```

Think this is the last we heard from Marvin.

**Comment by walro** [comment]
Seems like it works again(?):

```
Marvin Pingdom notification·May-27 8:27 AM

Pingdom: webhose.io is down
```

**Comment by walro** [comment]
But something looks off, perhaps always been off. Bagmati was down this morning, note the 404:

```
2018-05-28T06:11:00.180078+00:00 heroku[router]: at=info method=GET path= "/pingdom/webhook/<secret>?message=%7B%22check%22%3A+%221486749%22%2C+%22checkname%22%3A+%22Bagmati%22%2C+%22host%22%3A+%22ping.twingly.com%22%2C+%22action%22%3A+%22assign%22%2C+%22incidentid%22%3A+1486749%2C+%22description%22%3A+%22down%22%7D" host=twinglybot.herokuapp.com request_id=d7338f89-64c7-4dbe-8b47-f49820899c45 fwd="34.240.158.107" dyno=web.1 connect=0ms service=1ms status=404 bytes=462 protocol=http
```

It never reached the chat.

**Comment by jage** [comment]
Marvin did work sometimes, but we're moving on from HipChat. We might get a new bot, but it will probably not be Marvin.
